plugins {
	id "dev.architectury.loom" version "1.7-SNAPSHOT" apply false
	id "architectury-plugin" version "3.4-SNAPSHOT"
}

architectury {
	minecraft = project.minecraft_version
}

subprojects {
	apply plugin: "dev.architectury.loom"
	apply plugin: "maven-publish"

	dependencies {
		minecraft "com.mojang:minecraft:${project.minecraft_version}"
		mappings loom.officialMojangMappings()
	}
}

allprojects {
	apply plugin: "java"
	apply plugin: "architectury-plugin"

	archivesBaseName = project.archives_base_name
	version = project.mod_version
	group = project.maven_group

	repositories {
		mavenCentral()
		mavenLocal()
		maven { url = "https://maven.shedaniel.me/" }
		maven { url = "https://maven.blamejared.com/" }
		maven { url = "https://maven.parchmentmc.org" }
		maven { url = "https://maven.quiltmc.org/repository/release" }
		maven { url = "https://api.modrinth.com/maven" }
		maven { url = "https://maven.terraformersmc.com/releases/" }
		maven { url = "https://maven.jamieswhiteshirt.com/libs-release" }
		maven { url = "https://jitpack.io/" }
		maven { url = "https://maven.createmod.net" }
		maven { url = "https://maven.tterrag.com/" }
		maven { url = "https://raw.githubusercontent.com/Fuzss/modresources/main/maven/" }
		maven {
			name = "Resourceful Bees Maven"
			url = "https://maven.resourcefulbees.com/repository/maven-public/"
		}
		maven {
			url "https://squiddev.cc/maven/"
			content {
				includeGroup("cc.tweaked")
				includeModule("org.squiddev", "Cobalt")
			}
		}
	}

	tasks.withType(JavaCompile).configureEach {
		it.options.release = 17
	}

	java {
		withSourcesJar()
		sourceCompatibility = targetCompatibility = JavaVersion.VERSION_17
	}
}
